### ISSUE TITLE
zone graphics definition tool

### ISSUE THREAD

**Issue by AndyLoft** [AndyLoft/AB3D2_LevelED#12]
using the graphic definition buttons that allow wall, roof and floor definitions of a zone in the same window (buttons 18 & 19) the floor definition displays an incorrect graphic in the editors popup window

**Comment by 0xABADCAFE** [comment]
Can confirm this also happens in v303

**Comment by AndyLoft** [comment]
I have a fix for this, it is a typo in v303's code.

**Comment by AndyLoft** [comment]
fixed
