### ISSUE TITLE
Crash on Zone / Control Point Association

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#13]
Another control point issue.

When choosing to associate a zone with a control point (or an upper zone), if no zone is initially selected, choosing the control point first results in an Illegal function call crash.

**Comment by AndyLoft** [comment]
there is probably no check before testing the mouse click, might be an easy one (famous last words)

**Comment by AndyLoft** [comment]
I can't reproduce this crash, I may be not understanding how zone/point Association works, could you supply an idiots guide that leads to a crash?

**Comment by 0xABADCAFE** [comment]
Load a level.
Do not click or right click a zone, to ensure it remains unselected.
Choose the "associate zone with control point" tool. This will open a window saying that the left mouse is to select a control point, the right is to select the zone (I am doing this from memory just now so it could be the other way around).
Left click a control point.

It is possible that this has been fixed as a side effect of the work around moving and deleting control points.

**Comment by AndyLoft** [comment]
yes that crashed it.
I will look into putting a check to test if a zone is selected when selecting a control point, which should hopefully fix it.

**Comment by AndyLoft** [comment]
posted a build with a potential fix on eab
https://eab.abime.net/showpost.php?p=1621884&postcount=77
