### ISSUE TITLE
Feature Request: Level Statistics

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#17]
Since the original LevelEd303 version the menu item Level -> Statistics basically doesn't do anything. Assuming this was never implemented, it would be nice if it reported the following (some of which Level > Check Level already shows):
- Current / Max Points count (e.g. Points : 250 / 800)
- Current / Max Zone count (e.g. Zones: 32 / 256 - TBC if it's actually 256, lol)
- Current / Max Entity count
    - Some sub statistics on object count would be great, e.g.
        - Aliens, perhaps broken down by type
        - Objects, perhaps down by type

**Comment by AndyLoft** [comment]
The Level -> Statistics procedure/function is in the source code but is never called.
On looking over the code in this function it looks as if it is a much older piece of code that has not been updated to work with the 'system friendly' ( 🤣  ) new amos code and so brain damaged out. Tried calling it just for the hell of it and as expected, it crashes the editor 😞

**Comment by 0xABADCAFE** [comment]
That'll be why then.

**Comment by 0xABADCAFE** [comment]
The original editor no longer works for me at all, so I can't say. I must be missing a dependency. I'll install snoopdos (lol, autocorrect wanted to change that to snoopdog) and see if it's failing to open something.

**Comment by AndyLoft** [comment]
menu item Level -> Statistics now displays basic stats in the top right corner of the map window (I may expand on this)
![100](https://github.com/AndyLoft/AB3D2_LevelED/assets/89224328/c4f4ae5b-4dbe-47c9-b0dc-ea17620e33cf)
still need to add a 'tick' mark to the menu item to show current status of the item.
also there does not seem to be a way to have text with transparent background thus a small section of the map area is masked by the stats when displayed

**Comment by 0xABADCAFE** [comment]
That's looking great so far!

**Comment by AndyLoft** [comment]
expanded the stats to include alien objects, 'other' objects as well as total objects placed
![103](https://github.com/AndyLoft/AB3D2_LevelED/assets/89224328/26d96bf4-9fa9-4221-ae22-2b05989e7fd2)

**Comment by 0xABADCAFE** [comment]
I would say keep the strings a bit terser, perhaps something like:
- Aliens
- Objects
- Total Items
- Points
- Zones
- Control Points

**Comment by AndyLoft** [comment]
I agree, it does take up a chunk of screen real estate.
