### ISSUE TITLE
Bug: Level texts editor corrupt.

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#19]
This is an existing 303 issue. The dialogue that opens for editing the level texts (things that display when collecting, killing or destroying something) don't display properly and when editing go really messed up.

It is likely some sort of null termination issue given that there's some unprintable character at the end of the line.

**Comment by AndyLoft** [comment]
does the 'level intro text' tool work correctly? I only ask as I am not overly fluent in the amos language and it might be easier (if it does work) to look over the code for that and compare to the in level text procedure.

**Comment by AndyLoft** [comment]
ok so, it is when reloading that it is getting messed up, at least for me in a small test. in the 'original' T17 engine the text I type and save is correct but on reloading in the editor it is displayed with random extra/incorrect characters.

**Comment by 0xABADCAFE** [comment]
> is this the sort of thing you see in the editor? random characters in the text and some lines cut short? ![097](https://user-images.githubusercontent.com/89224328/243810257-7ec7a7f3-7059-40cb-a51b-40c1be89446f.png) does it save what is typed and just not reload it correct or is it all garbage in game as well?

Yep, that's pretty much it.

**Comment by AndyLoft** [comment]
I may have a fix for this soon, need to test some more but it looks promising so far.

**Comment by AndyLoft** [comment]
I have uploaded a build to eab for you to test
https://eab.abime.net/showpost.php?p=1621104&postcount=51

**Comment by 0xABADCAFE** [comment]
Roger that. I'll give it a whizz tomorrow.
