### ISSUE TITLE
Door/Lift Speed Limit

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#22]
Hopefully a low hanging fruit.

The editor restricts the maximum speed of a door or lift to 16, which is quite slow
 Level O has a drop trap where the lift falls at 200, so I suspect the value is at least an unsigned 8-bit property. I'd suggest the speed limit is raised to 255.

**Comment by AndyLoft** [comment]
good find. I have a fix for this.
did you want it for both doors and lifts?

**Comment by 0xABADCAFE** [comment]
Yes please.

**Comment by 0xABADCAFE** [comment]
I wonder what happens if a player stands on a lift that raises at that speed. If it just messes with the player position, not much, but if it adjusts the component velocity, that could be ... interesting.

**Comment by AndyLoft** [comment]
posted a build on eab
https://eab.abime.net/showpost.php?p=1622941&postcount=100

**Comment by 0xABADCAFE** [comment]
Works a treat. Set my first lift trap to fall at 64, worked flawlessly.

**Comment by AndyLoft** [comment]
cool beans, I think it may have the zone control point association mod in there too if you feel like testing that also, it will crash as normal if it doesn't

**Comment by AndyLoft** [comment]
If you are happy that there are no issues with the build I posted I will merge them with the main at some point this w/end (I will set the max speeds to 255 as you suggested just to be sure there is no unforeseen issues)
