### ISSUE TITLE
Feature Request: Level specific floor textures

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#33]
A planned engine enhancement will allow the inclusion of an optional, custom floor texture tile in each level directory, primarily to allow a bit more variation in appearance. This file will be in exactly the same format as the global file, all 16 tiles in a single chunky buffer. The engine will check if the file exists, and load it, falling back onto the global if it's not found.

Implementing the same behaviour in the editor when loading a level would ensure that texturing floors shows the same textures that will be used in the game.

**Comment by AndyLoft** [comment]
done.

**Comment by AndyLoft** [comment]
also level specific wall textures implemented for mods
