### ISSUE TITLE
Broken: No way to set initial Control Point for Alien

### ISSUE THREAD

**Issue by 0xABADCAFE** [AndyLoft/AB3D2_LevelED#8]
When editing alien properties, the Initial Target Control Point shows a zero value that is completely read only.
- The documentation for adding aliens suggests that this is to specify which control point the alien initially routes towards.
- TBC if this feature actually works in the game engine.
- A numeric entry that is range checked against the number of control points currently defined in the level would be better, or some form of prev/next button pair.
    - It would be ideal if this could centre/highlight the actual control point on the map, as there's currently no enumeration of them.
    - Alternatively, the ability to render the control point ID next to the control point as one of the menu view options.

**Comment by AndyLoft** [comment]
looking over the code, currently it is meant to set the Initial Target Control Point to the closest one which it may well do but for some reason is not displayed (or its broken lol).
